openapi: 3.1.0
info:
  version: "1.0"
  title: test-api
  summary: テスト用に作成したAPIです
servers:
  - url: "http://localhost:3000"
paths:
  "/users/{userId}":
    $ref: "paths/users/user-id.yaml"
  /user:
    $ref: "paths/user/index.yaml"
  /test:
    $ref: "paths/test/index.yaml"
components:
  schemas:
    User:
      $ref: "schemas/user.yaml"
    Task:
      $ref: "schemas/task.yaml"
