# https://qiita.com/yuya_sega/items/0b87e8e7d494f6fa3d69
# https://qiita.com/non_watanabe/items/f33983f3a6b4251d9a90
# https://zenn.dev/dozo/articles/1e0f542ea59244
openapi: '3.0.0'
info:
  title: test-api
  version: v1
paths:
  /tests:
    $ref: 'paths/test.yaml'
  /tests2:
    $ref: 'paths/test2.yaml'