import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";
import styles from "@/styles/layout.module.css";
import { MSWProvider } from "./msw-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <MSWProvider>
          {children}
          <Toaster className={styles.toaster} />
        </MSWProvider>
      </body>
    </html>
  );
}
